name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: app
          POSTGRES_USER: symfony
          POSTGRES_PASSWORD: ChangeMe
        options: >-
          --health-cmd="pg_isready -U symfony"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: |
          docker-compose -f symfony_sevopsPrjt/docker-compose.yaml build

      - name: Run Docker Compose
        run: |
          docker-compose -f symfony_sevopsPrjt/docker-compose.yaml up -d

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {30..0}; do
            if docker-compose -f symfony_sevopsPrjt/docker-compose.yaml exec -T database pg_isready -U symfony; then
              break
            fi
            echo 'PostgreSQL is unavailable - sleeping'
            sleep 1
          done

      - name: Install dependencies and run tests
        run: |
          docker-compose -f symfony_sevopsPrjt/docker-compose.yaml exec php8-sf6 composer install
          docker-compose -f symfony_sevopsPrjt/docker-compose.yaml exec php8-sf6 php bin/phpunit

      - name: Stop Docker Compose
        run: docker-compose -f symfony_sevopsPrjt/docker-compose.yaml down
